server:
  port: 8120
spring:
  application:
    name: lagou-cloud-eureka-server # 应用名称，会在Eureka中作为服务的id标识(serviceId)
eureka:
  instance:
    hostname: LagouCloudEurekaServerA
  client:
    service-url: # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone: http://LagouCloudEurekaServerB:8121/eureka/
    register-with-eureka: true # 集群需要在其他eureka注册自己
    fetch-registry: true #集群需要从Eureka Server获取其他Eureka服务信息,默认为true